name: fact_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip>=21.0
  - cudatoolkit=11.7  # Using CUDA 11.7 toolkit
  - pytorch=1.10.0=py3.8_cuda11.7_cudnn8_0  # PyTorch for CUDA 11.7
  - torchvision
  - torchaudio
  - pip:
    - rdkit-pypi
    - furo
    - numpy
    - sphinx
    - sphinx_rtd_theme==0.5.2
    - torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu117.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu117.html
    - torch-cluster -f https://data.pyg.org/whl/torch-1.10.0+cu117.html
    - torch-spline-conv -f https://data.pyg.org/whl/torch-1.10.0+cu117.html
    - torch-geometric==2.1.0
    - git+https://github.com/Chilipp/autodocsumm.git
    - captum==0.2.0
    - munch
    - gdown
    - cilog
    - typed-argument-parser==1.5.4
    - tensorboard
    - sympy
    - pyscf>=1.7.6
    - hydra-core
    - pygmtools
    - pyro-ppl
    - networkx