name: dig
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip>=21.0
  - pip:
    - rdkit-pypi
    - torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
    - furo
    - numpy
    - sphinx
    - sphinx_rtd_theme==0.5.2
    - pyg_lib 
    - torch_scatter 
    - torch_sparse 
    - torch_cluster 
    - torch_spline-conv
    - torch_geometric
    - pyro-ppl
    - git+https://github.com/Chilipp/autodocsumm.git
    - captum==0.2.0
    - munch
    - gdown
    - cilog
    - typed-argument-parser==1.5.4 
    - tensorboard
    - sympy
    - pyscf>=1.7.6
    - hydra-core
    - pygmtools
    - networkx ⁠