name: fact_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip>=21.0
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Replace X.X with the CUDA version that matches your system's CUDA installation
  - rdkit
  - pip:
    - torch-geometric
    - torch-sparse
    - torch-scatter
    - torch-cluster
    - torch-spline-conv
    - rdkit-pypi
    - furo
    - numpy
    - sphinx
    - sphinx_rtd_theme==0.5.2
    - git+https://github.com/Chilipp/autodocsumm.git
    - captum==0.2.0
    - munch
    - gdown
    - cilog
    - typed-argument-parser==1.5.4
    - tensorboard
    - sympy
    - pyscf>=1.7.6
    - hydra-core
    - pygmtools
    - pyro-ppl
    - networkx